### ISSUE TITLE
1.0.4 throws error on migration

### ISSUE THREAD

**Issue by michaelroper** [nystudio107/craft-templatecomments#3]
Hey Andrew!
That slight tweak you did for the 1.0.4 release seems to be causing a migration error on the console?

```
> ./craft migrate/all
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: craft\console\Request::isAjax'

in /Users/michael.roper/Sites/website-v3/vendor/yiisoft/yii2/base/Component.php:154

Stack trace:
#0 /Users/michael.roper/Sites/website-v3/vendor/nystudio107/craft-templatecomments/src/TemplateComments.php(92): yii\base\Component->__get('isAjax')
#1 /Users/michael.roper/Sites/website-v3/vendor/nystudio107/craft-templatecomments/src/TemplateComments.php(68): nystudio107\templatecomments\TemplateComments->addComponents()
...
```

(Craft v3.1.3)

**Comment by khalwat** [comment]
ups! Fixed in 1.0.5 -> https://github.com/nystudio107/craft-templatecomments/releases/tag/1.0.5
